In [3]:
import pandas,arcpy

In [17]:
import rpy2.robjects as robjects
from rpy2.robjects import r, pandas2ri
from rpy2.robjects.packages import importr

In [5]:
fields = [f.name for f in arcpy.ListFields("../data/shp/jbnt.gdb/jbnt") \
          if "Shape" not in f.name]

In [6]:
jbnt = pandas.DataFrame(arcpy.da.FeatureClassToNumPyArray("../data/shp/jbnt.gdb/jbnt",
                                                          fields))

In [7]:
jbnt.head()

,OBJECTID,BSM,YSDM,JBNTTBBH,TBBH,DLBM,DLMC,QSXZ,QSDWDM,QSDWMC,...,KCLX,KCDLBM,TKXS,LXDWMJ,XZDWMJ,TKMJ,TBMJ,JBNTMJ,DLBZ,SHAPE_Leng
0,1,1372097,2005010300,41172210320100010027,57,012,水浇地,30,4117221032010000000,杨集,...,,,0.0,0.0,2630.80,0.0,46047.16,43416.36,,1065.310282
1,2,1372124,2005010300,41172210320200040001,44,012,水浇地,30,4117230010010000000,平舆县飞地,...,,,0.0,0.0,430.80,0.0,51914.50,51483.70,,1603.499006
2,3,1372125,2005010300,41172210320200030028,41,012,水浇地,30,4117221032020000000,前桥,...,,,0.0,0.0,3620.51,0.0,101628.07,98007.56,,2202.234438
3,4,1372126,2005010300,41172210320200030030,43,012,水浇地,30,4117221032020000000,前桥,...,,,0.0,0.0,4474.92,0.0,131873.70,127398.78,,2129.505196
4,5,1372127,2005010300,41172210320200050001,45,012,水浇地,30,4117230010010000000,平舆县飞地,...,,,0.0,0.0,401.40,0.0,2284.68,1883.28,,348.385104

In [49]:
rs = '''
t <- function(dt){
 print(summary(dt))
}
'''

In [50]:
z = robjects.r(rs)

In [54]:
z(robjects.FloatVector(jbnt["TBMJ"]))

R object with classes: ('summaryDefault', 'table') mapped to:
<FloatVector - Python:0x00000199AB212A08 / R:0x00000199AD26C258>
[400.180000, 10468.480000, 22936.250000, 33975.798210, 44453.095000, 1578355.730000]